### PR TITLE
Added colorama for Windows ANSI support

### PR DESCRIPTION
**Pull request by spgill**
On Windows, the colorama package wraps stdout and translates ANSI codes to win32 API calls.

### CODE REVIEW

**Comment by cooperhammond** [comment]
Doesn't `colorama` only add ansi support for colors, or will it allow the codes that move the cursor as well?

**Comment by spgill** [comment]
As far as I can tell, it translates all ANSI codes, because the cursor works for me when I use it.

**Comment by cooperhammond** [comment]
So, did it not work before? I assume it didn't but it's worth checking.

**Comment by spgill** [comment]
Nah, it just prints the raw characters to the console. It's not pretty 😂

**Comment by cooperhammond** [comment]
Okay then, seems like a good trade off!

**Comment by cooperhammond** [comment]
Also, thanks for all of your support with this and getting windows support! I didn't ever expect to have windows support, so this helps a lot!

**Comment by spgill** [comment]
No problem at all! I love draftlog for nodejs, and having a similar package for Python is amazing; so I want to help make sure it works for everyone! 😄

**Pull request merged**
